name = "treeoneone"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[kv_namespaces]]
binding = "REQUESTS"
id = "REQUESTS_ID"
preview_id = "REQUESTS_PREVIEW_ID"

[env.production]
name = "treeoneone"
route = "https://treeoneone.org/*"
zone_id = "YOUR_ZONE_ID"

[env.preview]
name = "treeoneone-preview"
route = "https://preview.treeoneone.org/*"
zone_id = "YOUR_ZONE_ID" 